name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */10 * * *'  # Runs every 10 hours
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make empty commit
        run: |
          git config --global user.email "amenallah.zoghlami@etudiant-fst.utm.tn"
          git config --global user.name "Amen-code"
          git commit --allow-empty -m "Keep Streamlit app alive 🔄"
          git push
